### ISSUE TITLE
design API

### ISSUE THREAD

**Issue by meimeisuns** [sunmoyed/growus#11]
Let's do it on call!

**Comment by meimeisuns** [comment]
idk if we want to keep them but here are descriptions of the dummy endpoints I made to test the database connection:

**/exercises/create** inserts a single exercise for one user
**/exercises/clear** deletes all exercises created by a single user
**/exercises/all** shows all exercises created by a single user

**Comment by daiyi** [comment]
I see the first one in https://github.com/sunmoyed/growus/pull/18, perhaps you haven't pushed the rest of the changes yet? :P
