### ISSUE TITLE
set up database

### ISSUE THREAD

**Issue by daiyi** [sunmoyed/growus#17]
- [x] draft the database schema
- [x] hookup sqlite
- [x] add instructions to the readme if there's any installation steps

**Comment by meimeisuns** [comment]
okay I have a schema draft up on our gdoc, take a look when you have the time

**Comment by meimeisuns** [comment]
db schema is pretty rough right now, one concern I have is that there's lots of duplicates between users' exercise banks and workouts (some deets on gdoc)

this approach might get messy, so any ideas on other db organizations are welcome xD

**Comment by meimeisuns** [comment]
**enum deets**
some attributes will have predetermined options. We'll use a single number in the db, then map the numbers to appropriate strings in the app

**Comment by meimeisuns** [comment]
db kind of works!! [fe5b460](https://github.com/sunmoyed/growus/commit/fe5b46031dd70c755f6fb4850afd7c072b4c05a5)

tested it with a dummy api endpoint just to see if things were being put into tables.
You can test it by:
```
make server-dev
curl -X POST -F 'type=1' -F 'userId=1' -F 'name=stirring pb' -F 'description=forearm muscle power' http://localhost:9001/exercises/create
```
Then verify you put in an exercise by:
```
sqlite3
select * from Exercises
```
Running sqlite3 should make the sqlite prompt show up, which looks like this: `sqlite>`

I already inserted this exercise like, 5 times, idk if it shows up for you too, but try it out? xD
