### ISSUE TITLE
Implement random workout endpoint

### ISSUE THREAD

**Issue by meimeisuns** [sunmoyed/growus#2]
To Do (within this To Do):
- write a specification for how the data returned will be formatted
- implement api endpoint at `/workouts/random`
- use a fake set of exercises for now (maybe an array or something), before we implement the actual db

**Comment by meimeisuns** [comment]
(added to comment instead)

currently uses trivial pseudo-random algo and returns result as json object { "workout" : [ex1, ex2...] }.

If we want to use random workout to return realistic workouts, some small suggestions for future randomization:

- If we have categories of exercises, return appropriate number of exercises within random categories (eg. return one random long cardio exercise, and three floor exercises as one workout. Don't want 5 long cardio exercises or you'll die xD)
- adjust number of exercises according to level of in-shape-ness

**Comment by daiyi** [comment]
These are great suggestions! Let's make a new issue with that as the description, and then you can go ahead and close this one.
