### ISSUE TITLE
Optimize overview calendar dot rendering 

### ISSUE THREAD

**Issue by meimeisuns** [sunmoyed/growus#50]
(Goal: I want to see the markers for all the things I did each day on my overview calendar!)

Grow-us currently ties calendar dot rendering to fetching entries for pagination, so dots will come and go as you click to see more. We want to be able to see all the dots in one glance without clicking.

Included in this issue:
- splitting entries documents in firestore into a lite portion requested by the calendar (in monthly chunks), and then a separate detailed version that can be requested by the entry rendering
- creating a new watcher function to query the lite info for only the calendar
- editing the existing entries function to query for the full details
- creating a test database to try out the new data hierarchy
- splitting and rearranging existing data into the new data hierarchy

**Comment by daiyi** [comment]
closed by #52
